export default [
  {
    id: 1,
    username: 'COeVENer',
    createdAt: '27/03/2019',
    avatar: '/static/images/avatars/yaktocat.png',
    name: 'Joy Hurley',
    initial: 'JH',
  },
  {
    id: 2,
    username: 'owEsPEAn',
    createdAt: '31/03/2019',
    name: 'Saige Higgins',
    avatar: 'https://octodex.github.com/images/mcefeeline.jpg',
    initial: 'SH',
  },
  {
    id: 3,
    username: 'EatiOutI',
    createdAt: '03/04/2019',
    name: 'Yael Bradford',
    avatar: 'https://octodex.github.com/images/gracehoppertocat.jpg',
    initial: 'YB',
  },
  {
    id: 4,
    username: 'HaVentIv',
    createdAt: '04/04/2019',
    name: 'Gauge Knapp',
    initial: 'GK',
  },
  {
    id: 5,
    username: 'paTRaLAR',
    createdAt: '04/04/2019',
    name: 'Aryan Chavez',
    initial: 'AC',
  },
  {
    id: 6,
    username: 'keYerKLE',
    createdAt: '04/04/2019',
    name: 'Abel Vega',
    initial: 'AV',
  },
  {
    id: 7,
    username: 'COeVENer',
    createdAt: '27/03/2019',
    avatar: '/static/images/avatars/yaktocat.png',
    name: 'Joy Hurley',
    initial: 'JH',
  },
  {
    id: 8,
    username: 'owEsPEAn',
    createdAt: '31/03/2019',
    name: 'Saige Higgins',
    avatar: 'https://octodex.github.com/images/mcefeeline.jpg',
    initial: 'SH',
  },
  {
    id: 9,
    username: 'EatiOutI',
    createdAt: '03/04/2019',
    name: 'Yael Bradford',
    avatar: 'https://octodex.github.com/images/gracehoppertocat.jpg',
    initial: 'YB',
  },
  {
    id: 10,
    username: 'HaVentIv',
    createdAt: '04/04/2019',
    name: 'Gauge Knapp',
    initial: 'GK',
  },
  {
    id: 11,
    username: 'paTRaLAR',
    createdAt: '04/04/2019',
    name: 'Aryan Chavez',
    initial: 'AC',
  },
  {
    id: 12,
    username: 'keYerKLE',
    createdAt: '04/04/2019',
    name: 'Abel Vega',
    initial: 'AV',
  }
];
